_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
C:
    value: 5
batch:
    value: 64
epochs:
    value: 200000
learning_rate:
    value: 0.01
